import test from 'node:test';
import assert from 'node:assert/strict';
import { openDatabase, now, postBalanced } from '../src/db.js';
import { migrate } from '../src/migrate.js';
import { creditDeposit, failWithdrawal, purchasePlan, reserveWithdrawal } from '../src/finance.js';

function fixture(){const db=openDatabase(':memory:');migrate(db);const created=now();db.prepare(`INSERT INTO users(id,email,password_hash,referral_code,created_at) VALUES('user_1','u@example.com','x:y','REF1',?)`).run(created);db.prepare(`INSERT INTO wallets VALUES('wallet_1','user_1','UGX',?)`).run(created);return db;}
function fund(db,amount=100000){postBalanced(db,{reference:`fund_${amount}`,type:'ADJUSTMENT',entries:[{walletId:'wallet_1',bucket:'AVAILABLE',amount},{bucket:'GATEWAY_CLEARING',amount:-amount}]});}
const bucket=(db,name)=>Number(db.prepare('SELECT COALESCE(SUM(amount),0)n FROM ledger_entries WHERE wallet_id=? AND bucket=?').get('wallet_1',name).n);

test('wallet cannot go negative and committed capital is not withdrawable',()=>{const db=fixture();assert.throws(()=>purchasePlan(db,{userId:'user_1',planId:'plan_1',idempotencyKey:'no-money'}),/Insufficient/);fund(db,25000);purchasePlan(db,{userId:'user_1',planId:'plan_1',idempotencyKey:'buy'});assert.equal(bucket(db,'AVAILABLE'),0);assert.equal(bucket(db,'COMMITTED_CAPITAL'),25000);assert.throws(()=>reserveWithdrawal(db,{userId:'user_1',amount:1000,fee:0,phone:'+256700000000',idempotencyKey:'locked'}),/Insufficient/);db.close();});
test('plan purchase is idempotent and moves available to committed',()=>{const db=fixture();fund(db);const first=purchasePlan(db,{userId:'user_1',planId:'plan_1',idempotencyKey:'once'}),second=purchasePlan(db,{userId:'user_1',planId:'plan_1',idempotencyKey:'once'});assert.equal(first.id,second.id);assert.equal(bucket(db,'AVAILABLE'),75000);assert.equal(bucket(db,'COMMITTED_CAPITAL'),25000);db.close();});
test('successful verified payment credits exactly once; failed status does not credit',()=>{const db=fixture(),created=now();db.prepare(`INSERT INTO deposits(id,user_id,idempotency_key,amount,phone,status,gateway_reference,created_at,updated_at) VALUES('dep_1','user_1','d1',50000,'+256700000000','PENDING','TX-1',?,?)`).run(created,created);const verified={reference:'TX-1',status:'completed',currency:'UGX',amount:50000,fee:0,net_amount:50000};creditDeposit(db,'dep_1',verified);creditDeposit(db,'dep_1',verified);assert.equal(bucket(db,'AVAILABLE'),50000);db.prepare(`INSERT INTO deposits(id,user_id,idempotency_key,amount,phone,status,gateway_reference,created_at,updated_at) VALUES('dep_2','user_1','d2',50000,'+256700000000','PENDING','TX-2',?,?)`).run(created,created);assert.throws(()=>creditDeposit(db,'dep_2',{...verified,reference:'TX-2',status:'failed'}));assert.equal(bucket(db,'AVAILABLE'),50000);db.close();});
test('withdrawal locks funds, duplicate request does not relock, failure releases once',()=>{const db=fixture();fund(db);const a=reserveWithdrawal(db,{userId:'user_1',amount:20000,fee:600,phone:'+256700000000',idempotencyKey:'payout'}),b=reserveWithdrawal(db,{userId:'user_1',amount:20000,fee:600,phone:'+256700000000',idempotencyKey:'payout'});assert.equal(a.id,b.id);assert.equal(bucket(db,'AVAILABLE'),79400);assert.equal(bucket(db,'PENDING_WITHDRAWAL'),20600);failWithdrawal(db,a.id);failWithdrawal(db,a.id);assert.equal(bucket(db,'AVAILABLE'),100000);assert.equal(bucket(db,'PENDING_WITHDRAWAL'),0);db.close();});
test('ledger entries cannot be changed or deleted',()=>{const db=fixture();fund(db);const entry=db.prepare('SELECT id FROM ledger_entries LIMIT 1').get();assert.throws(()=>db.prepare('UPDATE ledger_entries SET amount=1 WHERE id=?').run(entry.id),/immutable/);assert.throws(()=>db.prepare('DELETE FROM ledger_entries WHERE id=?').run(entry.id),/immutable/);db.close();});
