import { balance, id, now, postBalanced, transaction } from './db.js';

export function walletFor(db,userId){const wallet=db.prepare('SELECT * FROM wallets WHERE user_id=?').get(userId);if(!wallet)throw new Error('Wallet not found');return wallet;}
export function creditDeposit(db, depositId, verified) {
  return transaction(db,()=>{const dep=db.prepare('SELECT * FROM deposits WHERE id=?').get(depositId);if(!dep)throw new Error('Deposit not found');if(dep.status==='SUCCESS')return dep;if(verified.reference!==dep.gateway_reference||verified.status!=='completed'||verified.currency!=='UGX'||Number(verified.amount)!==dep.amount)throw new Error('Gateway verification mismatch');db.prepare(`UPDATE deposits SET status='SUCCESS',fee=?,net_amount=?,gateway_metadata=?,updated_at=? WHERE id=? AND status='PENDING'`).run(Number(verified.fee||0),Number(verified.net_amount||dep.amount),JSON.stringify(verified),now(),dep.id);postBalanced(db,{reference:dep.gateway_reference,type:'DEPOSIT_SUCCESS',entries:[{walletId:walletFor(db,dep.user_id).id,bucket:'AVAILABLE',amount:dep.amount},{bucket:'GATEWAY_CLEARING',amount:-dep.amount}]});return db.prepare('SELECT * FROM deposits WHERE id=?').get(dep.id);});
}
export function purchasePlan(db,{userId,planId,idempotencyKey}) {return transaction(db,()=>{const prior=db.prepare("SELECT * FROM capital_positions WHERE id=?").get(`pos_${idempotencyKey}`);if(prior)return prior;const wallet=walletFor(db,userId),plan=db.prepare("SELECT * FROM funding_plans WHERE id=? AND status='ACTIVE'").get(planId);if(!plan)throw new Error('Plan unavailable');const amount=plan.fixed_plan_price||plan.minimum_amount;if(balance(db,wallet.id,'AVAILABLE')<amount)throw new Error('Insufficient available wallet');const created=now(),maturity=new Date(Date.now()+plan.duration_days*86400000).toISOString(),positionId=`pos_${idempotencyKey}`;db.prepare(`INSERT INTO capital_positions(id,user_id,plan_id,principal,status,started_at,matures_at,projected_return,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(positionId,userId,planId,amount,'ACTIVE',created,maturity,plan.projected_return_amount||0,created,created);postBalanced(db,{reference:positionId,type:'CAPITAL_COMMITTED',entries:[{walletId:wallet.id,bucket:'AVAILABLE',amount:-amount},{walletId:wallet.id,bucket:'COMMITTED_CAPITAL',amount}]});return db.prepare('SELECT * FROM capital_positions WHERE id=?').get(positionId);});}
export function reserveWithdrawal(db,{userId,amount,fee,phone,idempotencyKey}) {return transaction(db,()=>{const prior=db.prepare('SELECT * FROM withdrawals WHERE idempotency_key=?').get(idempotencyKey);if(prior)return prior;const wallet=walletFor(db,userId),total=amount+fee;if(balance(db,wallet.id,'AVAILABLE')+balance(db,wallet.id,'REALIZED_EARNINGS')<total)throw new Error('Insufficient withdrawable balance');let available=Math.min(balance(db,wallet.id,'AVAILABLE'),total),earnings=total-available;const wid=id('wdr'),created=now();db.prepare(`INSERT INTO withdrawals(id,user_id,idempotency_key,amount,fee,net_amount,phone,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(wid,userId,idempotencyKey,amount,fee,amount,phone,'PENDING',created,created);const entries=[{walletId:wallet.id,bucket:'PENDING_WITHDRAWAL',amount:total}];if(available)entries.push({walletId:wallet.id,bucket:'AVAILABLE',amount:-available});if(earnings)entries.push({walletId:wallet.id,bucket:'REALIZED_EARNINGS',amount:-earnings});postBalanced(db,{reference:wid,type:'WITHDRAWAL_PENDING',entries});return db.prepare('SELECT * FROM withdrawals WHERE id=?').get(wid);});}
export function failWithdrawal(db,withdrawalId){return transaction(db,()=>{const withdrawal=db.prepare('SELECT * FROM withdrawals WHERE id=?').get(withdrawalId);if(!withdrawal)throw new Error('Withdrawal not found');if(withdrawal.status==='FAILED')return withdrawal;if(withdrawal.status!=='PENDING'&&withdrawal.status!=='PROCESSING')throw new Error('Withdrawal cannot be failed');const wallet=walletFor(db,withdrawal.user_id),total=withdrawal.amount+withdrawal.fee;db.prepare("UPDATE withdrawals SET status='FAILED',updated_at=? WHERE id=?").run(now(),withdrawal.id);postBalanced(db,{reference:withdrawal.id,type:'WITHDRAWAL_FAILED',entries:[{walletId:wallet.id,bucket:'PENDING_WITHDRAWAL',amount:-total},{walletId:wallet.id,bucket:'AVAILABLE',amount:total}]});return db.prepare('SELECT * FROM withdrawals WHERE id=?').get(withdrawal.id);});}
