import { config } from './config.js';
import { openDatabase, now, id } from './db.js';
import { scryptSync, randomBytes } from 'node:crypto';

export const migrations = [
`CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,phone TEXT UNIQUE,password_hash TEXT NOT NULL,referral_code TEXT NOT NULL UNIQUE,referred_by TEXT REFERENCES users(id),role TEXT NOT NULL DEFAULT 'USER' CHECK(role IN('USER','ADMIN')),status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wallets(id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE REFERENCES users(id),currency TEXT NOT NULL DEFAULT 'UGX' CHECK(currency='UGX'),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ledger_entries(id TEXT PRIMARY KEY,wallet_id TEXT REFERENCES wallets(id),bucket TEXT NOT NULL CHECK(bucket IN('AVAILABLE','COMMITTED_CAPITAL','REALIZED_EARNINGS','REFERRAL','PENDING_WITHDRAWAL','GATEWAY_CLEARING','CAPITAL_CLEARING','EARNINGS_CLEARING','WITHDRAWAL_CLEARING')),amount INTEGER NOT NULL CHECK(amount<>0),type TEXT NOT NULL,reference TEXT NOT NULL,metadata TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,UNIQUE(type,reference,bucket,wallet_id));
CREATE TRIGGER IF NOT EXISTS ledger_immutable_update BEFORE UPDATE ON ledger_entries BEGIN SELECT RAISE(ABORT,'ledger entries are immutable'); END;
CREATE TRIGGER IF NOT EXISTS ledger_immutable_delete BEFORE DELETE ON ledger_entries BEGIN SELECT RAISE(ABORT,'ledger entries are immutable'); END;
CREATE TABLE IF NOT EXISTS business_pools(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,capital_raised INTEGER NOT NULL DEFAULT 0,capital_deployed INTEGER NOT NULL DEFAULT 0,revenue_realized INTEGER NOT NULL DEFAULT 0,expenses INTEGER NOT NULL DEFAULT 0,profit_realized INTEGER NOT NULL DEFAULT 0,distributable_profit INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS funding_plans(id TEXT PRIMARY KEY,pool_id TEXT REFERENCES business_pools(id),name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,category TEXT NOT NULL,short_description TEXT NOT NULL,description TEXT NOT NULL,currency TEXT NOT NULL DEFAULT 'UGX',minimum_amount INTEGER NOT NULL,maximum_amount INTEGER,fixed_plan_price INTEGER,duration_days INTEGER NOT NULL,projected_daily_rate TEXT,projected_total_rate TEXT,projected_return_amount INTEGER,return_mode TEXT NOT NULL CHECK(return_mode IN('VARIABLE','FIXED_ADMIN_CREDIT','REVENUE_SHARE')),payout_frequency TEXT NOT NULL,capital_return_policy TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',featured INTEGER NOT NULL DEFAULT 0,risk_level TEXT NOT NULL DEFAULT 'MEDIUM',sort_order INTEGER NOT NULL DEFAULT 0,starts_at TEXT,ends_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS capital_positions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),plan_id TEXT NOT NULL REFERENCES funding_plans(id),principal INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT 'UGX',status TEXT NOT NULL DEFAULT 'ACTIVE',started_at TEXT NOT NULL,matures_at TEXT NOT NULL,projected_return INTEGER NOT NULL DEFAULT 0,realized_return INTEGER NOT NULL DEFAULT 0,withdrawable_earnings INTEGER NOT NULL DEFAULT 0,last_payout_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS deposits(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),idempotency_key TEXT NOT NULL UNIQUE,amount INTEGER NOT NULL,fee INTEGER NOT NULL DEFAULT 0,net_amount INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'UGX',phone TEXT NOT NULL,network TEXT,status TEXT NOT NULL DEFAULT 'PENDING',gateway_reference TEXT UNIQUE,gateway_metadata TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS withdrawals(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),idempotency_key TEXT NOT NULL UNIQUE,amount INTEGER NOT NULL,fee INTEGER NOT NULL,net_amount INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'UGX',phone TEXT NOT NULL,network TEXT,status TEXT NOT NULL DEFAULT 'PENDING',gateway_reference TEXT UNIQUE,gateway_metadata TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS webhook_events(id TEXT PRIMARY KEY,event_key TEXT NOT NULL UNIQUE,event_type TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL,error TEXT,created_at TEXT NOT NULL,processed_at TEXT);
CREATE TABLE IF NOT EXISTS distribution_batches(id TEXT PRIMARY KEY,pool_id TEXT NOT NULL REFERENCES business_pools(id),idempotency_key TEXT NOT NULL UNIQUE,amount INTEGER NOT NULL,status TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL,executed_at TEXT);
CREATE TABLE IF NOT EXISTS distribution_items(id TEXT PRIMARY KEY,batch_id TEXT NOT NULL REFERENCES distribution_batches(id),position_id TEXT NOT NULL REFERENCES capital_positions(id),user_id TEXT NOT NULL REFERENCES users(id),amount INTEGER NOT NULL,created_at TEXT NOT NULL,UNIQUE(batch_id,position_id));
CREATE TABLE IF NOT EXISTS referrals(id TEXT PRIMARY KEY,referrer_id TEXT NOT NULL REFERENCES users(id),referred_id TEXT NOT NULL UNIQUE REFERENCES users(id),level INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS referral_rewards(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),source_user_id TEXT REFERENCES users(id),basis TEXT NOT NULL,source_reference TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(user_id,basis,source_reference));
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),type TEXT NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,read_at TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),category TEXT NOT NULL,subject TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS support_messages(id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL REFERENCES support_tickets(id),user_id TEXT NOT NULL REFERENCES users(id),message TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_audit_logs(id TEXT PRIMARY KEY,admin_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT,metadata TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_ledger_wallet_bucket ON ledger_entries(wallet_id,bucket,created_at);
CREATE INDEX IF NOT EXISTS idx_positions_user_status ON capital_positions(user_id,status);
CREATE INDEX IF NOT EXISTS idx_deposits_user_status ON deposits(user_id,status);
CREATE INDEX IF NOT EXISTS idx_withdrawals_user_status ON withdrawals(user_id,status);`
];

export function migrate(db) {
  db.exec('CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)');
  migrations.forEach((sql, index) => { if (!db.prepare('SELECT 1 FROM schema_migrations WHERE version=?').get(index + 1)) { db.exec(sql); db.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(index + 1, now()); } });
  seed(db);
}

function hashPassword(password) { const salt=randomBytes(16).toString('hex'); return `${salt}:${scryptSync(password,salt,64).toString('hex')}`; }
function seed(db) {
  const created=now();
  const settings={platform_name:'Money Habour',currency:'UGX',country:'Uganda',timezone:'Africa/Kampala',withdrawal_mode:'HYBRID',automatic_withdrawal_threshold:'100000',minimum_withdrawal:'5000',maximum_withdrawal:'5000000',daily_withdrawal_limit:'5000000',withdrawal_fee_percent:'3',deposit_fee_percent:'0',referral_basis:'PLATFORM_FEE',level_1_percent:'0',level_2_percent:'0',minimum_liquidity_reserve_percent:'20',projection_disclaimer:'Returns depend on realized business performance and are not guaranteed.',risk_disclaimer:'Business activity carries risk. Projected performance may differ from actual performance.'};
  for(const [key,value] of Object.entries(settings)) db.prepare('INSERT OR IGNORE INTO settings VALUES(?,?,?)').run(key,value,created);
  const pools=[['SMM Growth','Customer acquisition campaigns'],['Advertising','Measured advertising projects'],['AI Agents','AI agent infrastructure'],['Business Expansion','Inventory and approved expansion'],['Multi-business','Diversified business activities']];
  const plans=[['Starter Growth','starter-growth',25000,30],['Business Growth','business-growth',50000,30],['AI Infrastructure','ai-infrastructure',100000,30],['Scale Fund','scale-fund',250000,60],['Enterprise Pool','enterprise-pool',500000,90]];
  pools.forEach(([name,description],i)=>db.prepare('INSERT OR IGNORE INTO business_pools(id,name,description,created_at) VALUES(?,?,?,?)').run(`pool_${i+1}`,name,description,created));
  plans.forEach(([name,slug,price,days],i)=>db.prepare(`INSERT OR IGNORE INTO funding_plans(id,pool_id,name,slug,category,short_description,description,minimum_amount,maximum_amount,fixed_plan_price,duration_days,return_mode,payout_frequency,capital_return_policy,featured,risk_level,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(`plan_${i+1}`,`pool_${i+1}`,name,slug,pools[i][0],`Fund ${pools[i][1].toLowerCase()}.`,`An admin-editable funding plan connected to real ${pools[i][0]} activity.`,price,price,price,days,'VARIABLE','MATURITY','RETURN_AT_MATURITY',i<3?1:0,i<3?'MEDIUM':'HIGH',i,created,created));
  if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD&&!db.prepare('SELECT 1 FROM users WHERE email=?').get(process.env.ADMIN_EMAIL.toLowerCase())) { const userId=id('usr'); db.prepare(`INSERT INTO users(id,email,password_hash,referral_code,role,created_at) VALUES(?,?,?,?,?,?)`).run(userId,process.env.ADMIN_EMAIL.toLowerCase(),hashPassword(process.env.ADMIN_PASSWORD),randomBytes(5).toString('hex').toUpperCase(),'ADMIN',created); db.prepare('INSERT INTO wallets VALUES(?,?,?,?)').run(id('wal'),userId,'UGX',created); }
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1].replace(/\\/g,'/')}`).href) { const db=openDatabase(config().databasePath); migrate(db); console.log('Database migrations applied.'); db.close(); }
