import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { randomBytes, scryptSync, timingSafeEqual, createHmac } from 'node:crypto';
import { config, normalizeUgandaPhone } from './config.js';
import { openDatabase, id, now } from './db.js';
import { migrate } from './migrate.js';
import { balance, transaction } from './db.js';
import { creditDeposit, failWithdrawal, purchasePlan, reserveWithdrawal, walletFor } from './finance.js';
import { XdigitexPayService } from './payments/XdigitexPayService.js';

const cfg=config(),db=openDatabase(cfg.databasePath);migrate(db);
const pay=new XdigitexPayService({apiKey:cfg.xdigitexApiKey,baseUrl:cfg.xdigitexBaseUrl});
const publicDir=path.resolve('public');
const sessions=new Map();
const rate=new Map();
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
const body=async(req)=>{let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>1_000_000)throw new Error('Request too large');}try{return raw?JSON.parse(raw):{};}catch{throw new Error('Invalid JSON');}};
const hashPassword=(password)=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`;};
const verifyPassword=(password,stored)=>{const [salt,hash]=stored.split(':');return timingSafeEqual(Buffer.from(hash,'hex'),scryptSync(password,salt,64));};
const sessionToken=(userId)=>{const nonce=randomBytes(24).toString('hex'),sig=createHmac('sha256',cfg.sessionSecret).update(nonce).digest('hex'),token=`${nonce}.${sig}`;sessions.set(token,{userId,expires:Date.now()+604800000});return token;};
const auth=(req)=>{const token=(req.headers.authorization||'').replace(/^Bearer /,'')||(req.headers.cookie||'').match(/mh_session=([^;]+)/)?.[1];const session=sessions.get(token);if(!session||session.expires<Date.now())return null;return db.prepare('SELECT id,email,phone,role,status,referral_code FROM users WHERE id=?').get(session.userId);};
const requireUser=(req,res,admin=false)=>{const user=auth(req);if(!user||user.status!=='ACTIVE'||(admin&&user.role!=='ADMIN')){json(res,admin?403:401,{error:admin?'Admin access required':'Authentication required'});return null;}return user;};
const throttle=(req,res)=>{const key=req.socket.remoteAddress||'unknown',item=rate.get(key)||{count:0,reset:Date.now()+60000};if(Date.now()>item.reset){item.count=0;item.reset=Date.now()+60000;}item.count++;rate.set(key,item);if(item.count>120){json(res,429,{error:'Too many requests'});return false;}return true;};
const settings=()=>Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]));
const summary=(userId)=>{const wallet=walletFor(db,userId),get=b=>balance(db,wallet.id,b);return {available:get('AVAILABLE'),activeCapital:get('COMMITTED_CAPITAL'),realizedEarnings:get('REALIZED_EARNINGS'),pendingWithdrawal:get('PENDING_WITHDRAWAL'),referralEarnings:get('REFERRAL'),currency:'UGX'};};

async function api(req,res,url){
  if(req.method==='POST'&&url.pathname==='/api/register'){const p=await body(req);if(!p.password||p.password.length<10)throw new Error('Password must be at least 10 characters');const phone=normalizeUgandaPhone(p.phone),email=p.email?String(p.email).trim().toLowerCase():null,userId=id('usr'),created=now(),code=randomBytes(5).toString('hex').toUpperCase();transaction(db,()=>{const ref=p.referralCode?db.prepare('SELECT id FROM users WHERE referral_code=?').get(String(p.referralCode).toUpperCase()):null;db.prepare('INSERT INTO users(id,email,phone,password_hash,referral_code,referred_by,created_at) VALUES(?,?,?,?,?,?,?)').run(userId,email,phone,hashPassword(p.password),code,ref?.id||null,created);db.prepare('INSERT INTO wallets VALUES(?,?,?,?)').run(id('wal'),userId,'UGX',created);if(ref)db.prepare('INSERT INTO referrals VALUES(?,?,?,?,?)').run(id('ref'),ref.id,userId,1,created);});return json(res,201,{token:sessionToken(userId)});}
  if(req.method==='POST'&&url.pathname==='/api/login'){const p=await body(req),user=db.prepare('SELECT * FROM users WHERE email=? OR phone=?').get(String(p.login||'').toLowerCase(),(()=>{try{return normalizeUgandaPhone(p.login);}catch{return ''}})());if(!user||!verifyPassword(p.password||'',user.password_hash))return json(res,401,{error:'Invalid credentials'});return json(res,200,{token:sessionToken(user.id)});}
  if(req.method==='POST'&&url.pathname==='/api/logout'){const token=(req.headers.authorization||'').replace(/^Bearer /,'');sessions.delete(token);return json(res,200,{ok:true});}
  if(req.method==='GET'&&url.pathname==='/api/plans')return json(res,200,{plans:db.prepare("SELECT * FROM funding_plans WHERE status='ACTIVE' ORDER BY sort_order").all(),disclaimer:settings().projection_disclaimer});
  if(req.method==='GET'&&url.pathname==='/api/me'){const user=requireUser(req,res);if(!user)return;return json(res,200,{user,balances:summary(user.id),positions:db.prepare('SELECT cp.*,fp.name plan_name FROM capital_positions cp JOIN funding_plans fp ON fp.id=cp.plan_id WHERE cp.user_id=? ORDER BY cp.created_at DESC').all(user.id),transactions:db.prepare('SELECT type,reference,bucket,amount,created_at FROM ledger_entries WHERE wallet_id=? ORDER BY created_at DESC LIMIT 50').all(walletFor(db,user.id).id)});}
  if(req.method==='POST'&&url.pathname==='/api/deposits'){const user=requireUser(req,res);if(!user)return;const p=await body(req),amount=Number(p.amount);if(!Number.isSafeInteger(amount)||amount<1000)throw new Error('Minimum deposit is UGX 1,000');const key=String(req.headers['idempotency-key']||p.idempotencyKey||'');if(!key)throw new Error('Idempotency-Key is required');const prior=db.prepare('SELECT * FROM deposits WHERE idempotency_key=? AND user_id=?').get(key,user.id);if(prior)return json(res,200,prior);const phone=normalizeUgandaPhone(p.phone||user.phone),depositId=id('dep'),created=now();db.prepare(`INSERT INTO deposits(id,user_id,idempotency_key,amount,phone,network,status,created_at,updated_at) VALUES(?,?,?,?,?,'AUTO','PENDING',?,?)`).run(depositId,user.id,key,amount,phone,created,created);try{const result=await pay.initiateDeposit({amount,phone,description:`Money Habour deposit ${depositId}`,callbackUrl:`${cfg.appUrl}/deposit`,webhookUrl:`${cfg.appUrl}/api/webhooks/xdigitex-pay`});db.prepare('UPDATE deposits SET gateway_reference=?,gateway_metadata=?,updated_at=? WHERE id=?').run(result.reference,JSON.stringify(result),now(),depositId);return json(res,202,db.prepare('SELECT * FROM deposits WHERE id=?').get(depositId));}catch(error){db.prepare("UPDATE deposits SET status='FAILED',gateway_metadata=?,updated_at=? WHERE id=?").run(JSON.stringify({error:error.message}),now(),depositId);throw error;}}
  if(req.method==='POST'&&url.pathname==='/api/webhooks/xdigitex-pay'){const p=await body(req),eventKey=`${p.event||'unknown'}:${p.reference||'missing'}`;if(!p.reference||!['payment.completed','payment.failed'].includes(p.event))return json(res,400,{error:'Malformed event'});try{db.prepare('INSERT INTO webhook_events VALUES(?,?,?,?,?,?,?,?)').run(id('wh'),eventKey,p.event,JSON.stringify(p),'RECEIVED',null,now(),null);}catch(error){if(String(error).includes('UNIQUE'))return json(res,200,{received:true,duplicate:true});throw error;}const dep=db.prepare('SELECT * FROM deposits WHERE gateway_reference=?').get(p.reference);if(!dep)return json(res,404,{error:'Unknown payment reference'});try{if(p.event==='payment.completed'){const verified=await pay.paymentStatus(p.reference);creditDeposit(db,dep.id,verified);}else db.prepare("UPDATE deposits SET status='FAILED',updated_at=? WHERE id=? AND status='PENDING'").run(now(),dep.id);db.prepare("UPDATE webhook_events SET status='PROCESSED',processed_at=? WHERE event_key=?").run(now(),eventKey);return json(res,200,{received:true});}catch(error){db.prepare("UPDATE webhook_events SET status='FAILED',error=?,processed_at=? WHERE event_key=?").run(error.message,now(),eventKey);throw error;}}
  if(req.method==='POST'&&url.pathname==='/api/positions'){const user=requireUser(req,res);if(!user)return;const p=await body(req),key=String(req.headers['idempotency-key']||p.idempotencyKey||'');if(!key)throw new Error('Idempotency-Key is required');return json(res,201,purchasePlan(db,{userId:user.id,planId:p.planId,idempotencyKey:key}));}
  if(req.method==='POST'&&url.pathname==='/api/withdrawals'){const user=requireUser(req,res);if(!user)return;const p=await body(req),amount=Number(p.amount),s=settings(),minimum=Number(s.minimum_withdrawal),maximum=Number(s.maximum_withdrawal);if(!Number.isSafeInteger(amount)||amount<minimum||amount>maximum)throw new Error(`Withdrawal must be UGX ${minimum.toLocaleString()}–${maximum.toLocaleString()}`);const key=String(req.headers['idempotency-key']||p.idempotencyKey||'');if(!key)throw new Error('Idempotency-Key is required');const fee=Math.ceil(amount*Number(s.withdrawal_fee_percent)/100),withdrawal=reserveWithdrawal(db,{userId:user.id,amount,fee,phone:normalizeUgandaPhone(p.phone||user.phone),idempotencyKey:key});if(withdrawal.gateway_reference||withdrawal.status!=='PENDING')return json(res,200,withdrawal);const automatic=s.withdrawal_mode==='AUTOMATIC'||(s.withdrawal_mode==='HYBRID'&&amount<=Number(s.automatic_withdrawal_threshold));if(!automatic)return json(res,202,withdrawal);try{const result=await pay.createWithdrawal({amount,phone:withdrawal.phone});db.prepare("UPDATE withdrawals SET gateway_reference=?,gateway_metadata=?,status='PROCESSING',updated_at=? WHERE id=?").run(result.reference,JSON.stringify(result),now(),withdrawal.id);return json(res,202,db.prepare('SELECT * FROM withdrawals WHERE id=?').get(withdrawal.id));}catch(error){failWithdrawal(db,withdrawal.id);throw error;}}
  if(req.method==='GET'&&url.pathname==='/api/admin/overview'){const user=requireUser(req,res,true);if(!user)return;const data={users:db.prepare('SELECT COUNT(*) n FROM users').get().n,activeCapital:db.prepare("SELECT COALESCE(SUM(amount),0) n FROM ledger_entries WHERE bucket='COMMITTED_CAPITAL'").get().n,pendingWithdrawals:db.prepare("SELECT COALESCE(SUM(amount+fee),0) n FROM withdrawals WHERE status IN('PENDING','PROCESSING')").get().n,depositsToday:db.prepare("SELECT COALESCE(SUM(amount),0) n FROM deposits WHERE status='SUCCESS' AND date(created_at)=date('now')").get().n};return json(res,200,data);}
  if(req.method==='POST'&&url.pathname==='/api/support'){const user=requireUser(req,res);if(!user)return;const p=await body(req);if(!p.subject||!p.message)throw new Error('Subject and message are required');const ticket=id('tic'),created=now();transaction(db,()=>{db.prepare('INSERT INTO support_tickets VALUES(?,?,?,?,?,?,?)').run(ticket,user.id,p.category||'Other',String(p.subject).slice(0,120),'OPEN',created,created);db.prepare('INSERT INTO support_messages VALUES(?,?,?,?,?)').run(id('msg'),ticket,user.id,String(p.message).slice(0,5000),created);});return json(res,201,{id:ticket});}
  return json(res,404,{error:'Not found'});
}

export const server=http.createServer(async(req,res)=>{try{if(!throttle(req,res))return;const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);const clean=url.pathname==='/'?'index.html':url.pathname.replace(/^\//,'');const file=path.resolve(publicDir,clean);if(!file.startsWith(publicDir)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(200,{'Content-Type':'text/html'});return res.end(fs.readFileSync(path.join(publicDir,'index.html')));}const ext=path.extname(file),types={'.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.html':'text/html'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'",'Referrer-Policy':'same-origin'});fs.createReadStream(file).pipe(res);}catch(error){console.error(error.message);json(res,400,{error:error.message});}});

if(process.env.NODE_ENV!=='test')server.listen(cfg.port,()=>console.log(`Money Habour listening on http://localhost:${cfg.port}`));
